// <auto-generated />
using GarantiKitap.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GarantiKitap.Migrations
{
    [DbContext(typeof(ApplicationConnectionDb))]
    [Migration("20230525112312_DB-V1")]
    partial class DBV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GarantiKitap.Models.musteriler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("adSoyad")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("telefon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("musteriler");
                });
#pragma warning restore 612, 618
        }
    }
}
